### ISSUE TITLE
JS Package Version Information

### ISSUE THREAD

**Issue by imaaxa** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#44]
Is there a way to get a list of specific package versions used in the book?

Seems like too many of these packages have changed since the release, and are causing issues.

Example: I had to downgrade node-fetch from 3.X.X to 2.6.1 to get stylelint to run. Now, stylelint crashes after giving 68 problems (68 errors, 0 warnings).

I have spent hours diagnosing problems on **every** step of the dev environment set up. Just because I find a solution for that issue, does not mean it is the correct one. For all I know, it could be causing the next one.

Specifying which package versions to use, so we can lock it down, would be a big help.

**Comment by imaaxa** [comment]
I found the final [package.json](https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/final/web/themes/custom/alps_trips/package.json) file. It contains the information I asked for.

**Comment by aXb0t** [comment]
Thanks for this. Even though the issue is closed it is helpful. Leaving a couple notes in case others come across this.

Referencing the `final` branch `package.json` is useful for solving some development environment issues. However, I came across a few issues where package versions in the `final` branch are also not working. 

ESLint installs at greater than version 8 by default now, which causes eslintrc.json errors https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/issues/52

Drupal core Stylelint version is beyond version 14, which seems to cause Stylelint rules and configuration conflicts.

It seems to me to be impossible to keep a book and example repo up to date with changes in all the various dependencies.
